/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 controller.gltf --transform 
Files: controller.gltf [646.13KB] > /Users/asd/Desktop/controller_gltf/controller-transformed.glb [184.73KB] (71%)
Author: CoryRichards (https://sketchfab.com/CoryRichards)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gamecube-controller-21983501bac64993ac09cdc7936ffdf2
Title: Gamecube Controller
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/controller-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.phong2SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/controller-transformed.glb')
